[package]
name = "oncapintudacom3metros_bot"
version = "0.1.0"
authors = ["Caio <caio@guerras.com>"]
edition = "2021"

[dependencies]
teloxide = "0.3.1"
openai = "1.0.0-alpha.6"
tokio-stream = "0.1.12"